# Generated by Django 5.2 on 2026-08-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idol_name', models.CharField(max_length=50)),
                ('event_category', models.CharField(max_length=50)),
                ('event_title', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('event_location', models.CharField(max_length=100)),
            ],
        ),
    ]
