# Generated by Django 5.2 on 2026-09-01 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country_info',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Idol_info',
            fields=[
                ('idol_id', models.AutoField(primary_key=True, serialize=False)),
                ('idol', models.CharField(max_length=100)),
                ('calendar_id', models.CharField(max_length=255)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, related_name='idols', to='inuwasi_schedule.country_info')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(blank=True, max_length=100, null=True)),
                ('event_title', models.CharField(max_length=250)),
                ('event_date', models.DateField()),
                ('event_address', models.CharField(blank=True, default='주소 없음', max_length=300, null=True)),
                ('event_location', models.CharField(blank=True, default='위치 없음', max_length=200, null=True)),
                ('idol', models.ForeignKey(db_column='idol_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='inuwasi_schedule.idol_info')),
            ],
        ),
    ]
