# Generated by Django 5.2 on 2026-09-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inuwasi_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country_info',
            options={'verbose_name': '국가', 'verbose_name_plural': '국가 목록'},
        ),
        migrations.AlterModelOptions(
            name='idol_info',
            options={'verbose_name': '아이돌', 'verbose_name_plural': '아이돌 목록'},
        ),
        migrations.AlterModelOptions(
            name='schedule_info',
            options={'verbose_name': '스케줄', 'verbose_name_plural': '스케줄 목록'},
        ),
        migrations.AlterModelTable(
            name='country_info',
            table='country',
        ),
        migrations.AlterModelTable(
            name='idol_info',
            table='idol',
        ),
        migrations.AlterModelTable(
            name='schedule_info',
            table='schedule',
        ),
    ]
