# Generated by Django 5.2 on 2026-08-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inuwasi_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_info',
            name='event_title',
            field=models.CharField(max_length=200),
        ),
    ]
