# Generated by Django 5.2 on 2026-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inuwasi_schedule', '0002_alter_schedule_info_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_info',
            name='event_category',
            field=models.CharField(max_length=100),
        ),
    ]
