# Generated by Django 5.2 on 2026-08-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inuwasi_schedule', '0003_alter_schedule_info_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_info',
            name='event_date',
            field=models.DateField(),
        ),
    ]
