# Generated by Django 5.2 on 2026-08-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inuwasi_schedule', '0004_alter_schedule_info_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_info',
            name='event_location',
        ),
    ]
