# Generated by Django 5.2 on 2026-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inuwasi_schedule', '0005_remove_schedule_info_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_info',
            name='event_address',
            field=models.CharField(blank=True, default='주소 없음', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='schedule_info',
            name='event_location',
            field=models.CharField(default='위치 없음', max_length=200),
        ),
    ]
